	<footer>
		<div class="content">
			<nav>
                <a href="<?= $this->baseUrl; ?>/">Home</a>
                <a href="<?= $this->baseUrl; ?>/collection">Collection</a>
            </nav>
            <img src="<?= $this->baseUrl; ?>/img/logo.png" alt="bsl concept logotype">
            <p>© MELART 2018</p>
            <div class="clear"></div>
		</div>
	</footer>
	<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/jquery.bxslider.css">
    <script src="<?php echo $this->baseUrl; ?>/js/jquery-3.2.1.min.js"></script>
    <script src="<?php echo $this->baseUrl; ?>/js/jquery.bxslider.js"></script>
    <script src="<?php echo $this->baseUrl; ?>/js/main.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/jquery.fancybox.min.css" />
    <script src="<?php echo $this->baseUrl; ?>/js/jquery.fancybox.min.js"></script>
	</body>
</html>