<?php echo $this->render('header.phtml'); ?>
	<?php echo $this->render('slider.phtml'); ?>
	<div class="wrapper">
		<div class="content">
			<h1 class="page-title"><span>Melart Home</span> - Armchairs, sofas - About brand</h1>
			<p id="about">To give you <strong>maximum</strong> comfort, Melart manufactures all its models in Europe according to a unique know-how. Always anxious to offer you the highest possible comfort, Melart only selects <strong>high quality materials</strong>. Melart foams and linings are used for the best bedding. These will offer you <strong>unmatched comfort</strong> and great resistance over the years.</p>
		</div>
		<?php echo $this->render('spacer.phtml'); ?>
	</div>
<?php echo $this->render('footer.phtml'); ?>