<?php echo $this->render('header.phtml'); ?>
	<?php echo $this->render('slider.phtml'); ?>
	<div class="wrapper">
		<div class="content">
			<h1 class="page-title"><span>Melart Home</span> - Armchairs, sofas - Contact</h1>
			<ul id="contact">
				<li class="point"><strong>Besolux</strong></li>
				<li>Rue du Chemin de Fer 17B</li>
				<li>L-8057 Bertrange</li>
				<li>Luxembourg</li>
				<li>+352 26 31 36 88</li>
				<li>support@micadoni.com</li>
				<li>If you have any queries, please do not hestitate to contact us.</li>
			</ul>
		</div>
		<?php echo $this->render('spacer.phtml'); ?>
	</div>
<?php echo $this->render('footer.phtml'); ?>