<?php echo $this->render('admin/headerAdmin.phtml'); ?>
	<div class="wrapper">
		<div class="content">
			<?php echo $this->render('admin/menu.phtml'); ?>
			<?= $this->messages[0] ?>
			<h1>Add category</h1>
			<form class="standard-form" method="POST" action="<?php echo $this->baseUrl; ?>/admin/add-category">
				<label class="required">Category name</label>
				<input type="text" name="category_name" required>
				<label>Category description</label>
				<textarea name="category_description"></textarea>
				<input id="submit" type="submit" value="Add category">
			</form>
		</div>
	</div>
<?php echo $this->render('admin/footerAdmin.phtml'); ?>