<?php echo $this->render('admin/headerAdmin.phtml'); ?>
	<div class="wrapper">
		<div class="content">
			<?php echo $this->render('admin/menu.phtml'); ?>
			<?= $this->messages[0] ?>
			<h1>Edit product</h1>
			<form class="standard-form" method="POST" action="<?php echo $this->baseUrl; ?>/admin/update-product">
				<input type="hidden" name="product_id" value="<?= $this->product->product_id; ?>">
				<label class="required">Product name</label>
				<input type="text" name="product_name" value="<?= $this->product->product_name; ?>" required>
				<label class="required">Product price</label>
				<input type="text" name="product_price" value="<?= $this->product->product_price; ?>" required>
				<label class="required">Product description</label>
				<textarea name="product_description" required><?= $this->product->product_description; ?></textarea>
				<label class="required">Belongs to category</label>
				<select name="belongs_to_category">
					<option value="<?= $this->product->belongs_to_category; ?>"><?= $this->category->category_name; ?></option>
					<?php for ($i=0; $i < count($this->categories); $i++): ?>
						<option value="<?= $this->categories[$i]->category_id ?>"><?= $this->categories[$i]->category_name ?></option>
					<?php endfor; ?>
				</select>
				<input id="submit" type="submit" value="Save">
			</form>
			<h2>Add new photos</h2>
			<form class="standard-form" method="POST" action="<?php echo $this->baseUrl; ?>/admin/add-product-images" enctype="multipart/form-data">
				<label class="required">Choose photos</label>
				<input type="file" name="images[]" multiple required>
				<input type="hidden" name="product_id" value="<?= $this->product->product_id; ?>">
				<input id="submit" type="submit" value="Add images">
			</form>
			<p class='ajax-message'>Image order changed succesfully.</p>
			<?php if (count($this->images)): ?>
				<h2>Manage photos</h2>
				<div id="photos">
					<?php for ($i=0; $i < count($this->images); $i++): ?>
						<div class="item" data-id="<?= $this->images[$i]->product_image_id; ?>">
							<img src="<?= $this->baseUrl; ?>/products/min/<?= $this->images[$i]->image; ?>" alt="">
							<div class="manage">
								<a onclick="return confirm('Do you really want to delete this image?')" href="<?= $this->baseUrl; ?>/admin/delete-image/image_id/<?= $this->images[$i]->product_image_id; ?>/product_id/<?= $this->product->product_id; ?>">Delete image</a>
							</div>
						</div>
					<?php endfor; ?>
				</div>
			<?php endif; ?>
			<?php if(count($this->variants)): ?>
			<h2>Product variants</h2>
				<div id="products">
					<?php 
						$product_images = new Application_Model_DbTable_ProductImages();
						for ($i=0; $i < count($this->variants); $i++):
							$images = $product_images->fetchAll(
								$product_images
									->select()
									->where('belongs_to_product = ?', $this->variants[$i]
									->product_id)
									->order('image_order ASC')
							);
							if (count($images)) {
								$img = $images[0]->image;
							} else $img = 'image.jpg';
					?>
							<div class="item">
								<img src="<?= $this->baseUrl; ?>/products/min/<?= $img; ?>" alt="<?= $this->variants[$i]->product_name; ?>">
								<h2><?= $this->variants[$i]->product_name; ?></h2>
								<div class="manage">
									<a href="<?= $this->baseUrl; ?>/admin/edit-variant/id/<?= $this->variants[$i]->product_id; ?>">Edit</a>
									<a href="<?= $this->baseUrl; ?>/admin/delete-variant/id/<?= $this->variants[$i]->product_id; ?>" onclick="return confirm('Do you really want to delete this variant?')">Delete</a>
								</div>
							</div>
					<?php endfor; ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
<?php echo $this->render('admin/footerAdmin.phtml'); ?>