<?php echo $this->render('admin/headerAdmin.phtml'); ?>
	<div class="wrapper">
		<div class="content">
			<?php echo $this->render('admin/menu.phtml'); ?>
			<?= $this->messages[0] ?>
			<h1>Manage products</h1>
			<div id="products">
				<?php 
					$product_images = new Application_Model_DbTable_ProductImages();
					for ($i=0; $i < count($this->products); $i++):
						$images = $product_images->fetchAll(
							$product_images
								->select()
								->where('belongs_to_product = ?', $this->products[$i]
								->product_id)
								->order('image_order ASC')
						);
						if (count($images)) {
							$img = $images[0]->image;
						} else $img = 'image.jpg';
				?>
						<div class="item">
							<img src="<?= $this->baseUrl; ?>/products/min/<?= $img; ?>" alt="<?= $this->products[$i]->product_name; ?>">
							<h2><?= $this->products[$i]->product_name; ?></h2>
							<div class="manage">
								<a href="<?= $this->baseUrl; ?>/admin/edit-product/id/<?= $this->products[$i]->product_id; ?>">Edit</a>
								<a href="<?= $this->baseUrl; ?>/admin/delete-product/id/<?= $this->products[$i]->product_id; ?>" onclick="return confirm('Do you really want to delete this product?')">Delete</a>
							</div>
						</div>
				<?php endfor; ?>
			</div>
		</div>
	</div>
<?php echo $this->render('admin/footerAdmin.phtml'); ?>