<?php echo $this->render('admin/headerAdmin.phtml'); ?>
	<div class="wrapper">
		<div class="content">
			<?php echo $this->render('admin/menu.phtml'); ?>
			<?= $this->messages[0] ?>
			<h1>Manage slides</h1>
			<div id="categories">
				<?php for ($i=0; $i < count($this->slides); $i++): ?>
					<div class="category">
						<p><?= $this->slides[$i]->name; ?></p>
						<div class="manage">
							<a href="<?= $this->baseUrl; ?>/admin/edit-slide/id/<?= $this->slides[$i]->slide_id; ?>">Edit</a>
						</div>
						<div class="clear"></div>
					</div>
				<?php endfor; ?>
			</div>
		</div>
	</div>
<?php echo $this->render('admin/footerAdmin.phtml'); ?>