<nav>
	<a href="<?php echo $this->baseUrl; ?>/admin/panel">Add product</a>
	<a href="<?php echo $this->baseUrl; ?>/admin/add-category">Add category</a>
	<a href="<?php echo $this->baseUrl; ?>/admin/manage-categories">Manage categories</a>
	<a href="<?php echo $this->baseUrl; ?>/admin/manage-products">Manage products</a>
	<a href="<?php echo $this->baseUrl; ?>/admin/manage-slides">Manage slides</a>
</nav>