<?php echo $this->render('header.phtml'); ?>
	<div class="wrapper" id="products-wrapper">
		<div id="products">
			<div class="content">
				<h1 class="page-title"><span>Micadoni Home</span> - <?= $this->category->category_name; ?></h1>
				<nav id="categories">
					<a href="<?= $this->baseUrl; ?>/collection">Collection</a>
					<?php for($i=0; $i<count($this->categories); $i++): ?>
						<?php if ($this->categories[$i]->category_id == $this->category->category_id) {
							$active = 'class="active"';
						} else $active = null;
						?>
						<a <?= $active; ?> href="<?= $this->baseUrl; ?>/collection/<?= $this->categories[$i]->category_nicelink; ?>,<?= $this->categories[$i]->category_id; ?>"><?= $this->categories[$i]->category_name; ?></a>
					<?php endfor; ?>
				</nav>
				<div id="products">
					<?php 
						$products_images = new Application_Model_DbTable_ProductImages();
						for ($i=0; $i < count($this->products); $i++):
							$images_selected = $products_images->fetchAll($products_images->select()->where('belongs_to_product = ?', $this->products[$i]->product_id)->order('image_order ASC'));
							if (count($images_selected)) {
								$image = $images_selected[0]->image;
						} else $image = 'not-available.png';
					?>
						<a href="<?= $this->baseUrl; ?>/product/<?= $this->products[$i]->product_nicelink; ?>,<?= $this->products[$i]->product_id; ?>">
							<div class="item">
								<img src="<?= $this->baseUrl; ?>/products/min/<?= $image; ?>" alt="<?= $this->products[$i]->product_name; ?>">
								<h3><?= $this->products[$i]->product_name; ?></h3>
								<p>&euro;<?= $this->products[$i]->product_price; ?></p>
							</div>
						</a>
					<?php endfor; ?>
				</div>
			</div>
		</div>
	</div>
	<?php echo $this->render('spacer.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>